baseURL:                 https://ankhterus.github.io/
theme:                   hugo-orbit-theme

defaultcontentlanguage:  fr
disable404:              true
disablerss:              true
disablesitemap:          true

services:
  googleAnalytics:
    ID: G-F13HE46DP3

params:
  # Metadata
  author:                Nicolas Gagnière
  title:                 Nicolas Gagnière - CV
  description:           Nicolas Gagnière CV
  styles:                styles-6.css

# Sidebar
  profile:
    name:                Nicolas Gagnière
    tagline:             Amateur de Bretzels
    avatar:              profile.png

  contact:
    enable:              true
    list:
      - class:           email
        icon:            fa-envelope
        url:             mailto:nicolas.gagniere@gmail.com
        title:           nicolas.gagniere@gmail.com

      - class:           linkedin
        icon:            fa-linkedin
        url:             //linkedin.com/in/nicolasgagniere
        title:           linkedin.com/in/nicolasgagniere

      - class:           website
        icon:            fa-globe
        url:             //ankhterus.github.io/
        title:           ankhterus.github.io

      - class:           github
        icon:            fa-github
        url:             //github.com/Ankhterus
        title:           github.com/Ankhterus

  education:
    enable:              true
    list:
      - degree:          Doctorat de Bioinformatique
        college:         Université de Strasbourg / IGBMC
        dates:           sept. 2006 - oct. 2009

  language:
    enable:              true
    list:
      - language:        Français
        level:           Natif
      - language:        Anglais
        level:           Courant

  interests:
    enable:              true
    list:
      - interest:        Escalade
      - interest:        Parapente
      - interest:        Geekeries

# Main content
  summary:
    enable:              true
    icon:                fa-user
    summary:             |
        Parti d'un bac technologique en biologie (STL BGB), d'études courtes en études courtes en passant par une thèse en Bioinformatique, je me suis peu à peu réorienté vers l'informatique pour laquelle j'ai une affinité particulière après avoir été élevé par un C64 à grand renforts de POKE et PEEK.

        Mes passages au sein de plusieurs équipes hétéroclites et pluridisciplinaires et ma curiosité m'ont permis de régulièrement challenger et étendre mes compétences de développement en divers langages/_frameworks_, ainsi qu'en administration systèmes et réseaux Linux.

        En combinaison avec une veille technologique constante, j'ai ainsi acquis une bonne vision globale de l'informatique en général, ce qui me permet de m'orienter relativement rapidement vers une solution.

  experiences:
    enable:              true
    icon:                fa-briefcase
  jobs:
    list:
      # - position:        À la recherche de l'emploi perdu
      #   dates:           Actuellement
      #   company:         Continent perdu Bhâ-Rihnoâh
      #   details:         |
      #     Je pars à l'aventure au sein de la jungle de la recherche d'emploi afin de retrouver l’artefact du _CDI-au-projet-sympa-et-stimulant_. Si vous recherchez un _lead developer_ sur Strasbourg ou sa région, n'hésitez pas à me contacter.

      - position:        SysSecOps
        dates:           février 2024 - Aujourd'hui
        company:         Région de Strasbourg
        details:         |
          Bien conscient des enjeux liés à la sécurité des données, des applications et des infrastructures, je mets à profit tout le savoir accumulé lors de mes expériences passées.

      - position:        Architecte Java et DevOps
        dates:           juin 2018 - janvier 2024
        company:         Astek, Strasbourg
        details:         |
          Durant près de 6 ans, j'ai développé de très solides compétences dans les technologies des conteneurs et de leur orchestration. Ainsi, j'ai participé à l'évangélisation de ces dernières parmi l'équipe d'Astek Strasbourg et quelques-uns de ses clients en offrant mon support sur de nombreux projets. Ce travail transverse m'a permis de définir et de mettre en place les bonnes pratiques DevOps et de supervision avec l'aide de mes différents collègues impliqués.

          Ces connaissances m'ont aussi servi à construire la plate-forme d'intégration continue du [groupe Astek](https://astekgroup.fr/) (basée sur les outils [GitLab](https://gitlab.com/), [GitLab CI/CD](https://docs.gitlab.com/ee/ci/), [SonarQube](https://www.sonarsource.com/products/sonarqube/) et [Sonatype Nexus Repository](https://www.sonatype.com/products/sonatype-nexus-repository) déployés dans un environnement [Kubernetes](https://kubernetes.io/)), qui est utilisée lors de mon départ par une petite centaine de collaborateurs du groupe à l'international.

          En parallèle, j'ai approfondi mes connaissances Java en acquérant des compétences très pointues sur le _framework_ [Spring/Spring Boot](https://spring.io/), en ayant travaillé à la conception de nouvelles applications, en réalisant des audits de performance et de sécurité applicatives et en contribuant à de la tierce maintenance applicative. J'ai aussi développé de nouvelles compétences en applications Web monopages (_Single-Page Application_) avec les _frameworks_ [Angular](https://angular.io/) et [Vue.js](https://vuejs.org/).

          Principaux clients : [Air France](https://wwws.airfrance.fr/), [ArianeGroup](https://www.ariane.group/), [ClinFlows](https://clinflows.com/), [CNIEL](https://www.filiere-laitiere.fr/), [EPELFI](https://www.livrefoncier.fr/), [Savencia](https://www.savencia.com/), [TNT/FedEx](https://www.tnt.com/)

      - position:        Directeur technique
        dates:           oct. 2010 - janv. 2018
        company:         Bionext S.A., Strasbourg
        details:         |
          J'ai dirigé l'équipe technique de 4 personnes (3 permanents et 1 temps partiel), en charge du développement et du déploiement de _BioSight_, une application permettant la comparaison de surfaces moléculaires dans le cadre de la recherche et du développement de cibles thérapeutiques à l'aide d'un algorithme développé en interne par l'équipe R&D.

          Je me suis occupé personnellement d'intégrer cet algorithme au sein d'une nouvelle architecture de calculs distribués. Cela comprend :

          * la gestion de l'_Extract-Transform-Load_ des données au sein de _HBase_ et des index _Elasticsearch_,
          * le développement de _jobs Mapreduce_ et leur organisation en _workflows Oozie_
          * la mise à disposition de l'architecture de calculs au portail _BioSight_ par l'intermédiaire d'un _WebService REST_,
          * le déploiement _bare-metal_ des serveurs à l'aide de _MAAS_ et d'_Ansible_.

          Tâches annexes :

          * développement du logiciel de visualisation moléculaire interne _BioViz_ (Java),
          * déploiement de toute l'infrastructure du site de Strasbourg (serveurs, stockages réseaux, postes clients, git, _team chat_, wiki, DNS dynamique, sauvegardes...) accessible de manière sécurisée par certificats SSH et TLS.

      - position:        Doctorant chercheur
        dates:           sept. 2006 - oct. 2009
        company:         IGBMC, Illkirch-Graffenstaden
        details:         |
          J'ai développé une suite logicielle permettant de traiter et d'annoter les données de séquençage issues de plusieurs banques d'ADNc de tissus de l'annélide polychète _Alvinella pompejana_ (ver de Pompéi) afin de l'étudier sous différents aspects (phylogénétique moléculaire, résistances aux conditions extrêmes...).

          Cette suite a été développée en Tcl/Tk afin d'être intégrée à la plate-forme logicielle du laboratoire développée dans ce même langage. Un site Web permettant aux membres du consortium _Alvinella_ de parcourir le résultat de ces annotations a été développé en PHP4.

          Résumé: http://www.theses.fr/2009STRA6160

          Manuscript: [Thèse N.Gagnière 2009](/assets/docs/TheseGagniere2009.pdf)

  projects:
    enable:              true
    icon:                fa-archive
    # intro:             |
    list:
      - title:           Plate-forme d'intégration continue du groupe Astek
        tagline:         |
          Construction, support, maintenance et évolution de la PIC nationale du groupe Astek, utilisée pour héberger les projets internes et les projets de clients souhaitant externaliser le processus de développement.

          Technologies : Kubernetes, K3s, GitLab, GitLab CI/CD, SonarQube, Nexus Repository

      - title:           BioSight
        url:             https://biosight.bionext.com/
        tagline:         |
          Portail d'accès _Software as a Service_ de BioSight, application principale de Bionext permettant la comparaison de surfaces moléculaires dans le cadre de la conception de médicaments.

          Technologies : Hadoop, YARN/MapReduce2, HBase, Oozie, Elasticsearch, Hibernate, Jersey

      - title:           Alvinella cDNA
        url:             https://lbgi.fr/Alvinella/
        tagline:         |
          Portail de partage et de recherches au sein des résultats de traitements et d'annotations des données de séquençage d'_Alvinella pompejana_.

          Technologies : PHP4, ADOdb, PostgreSQL, Smarty, MVC. (Portage Symfony 1.0/Doctrine non finalisé)

  skills:
    enable:              true
    icon:                fa-rocket
    list:
      - section:         Cloud Native
      - skill:           Kubernetes
        level:           90%
      - skill:           K3s
        level:           90%
      - skill:           Docker / Docker compose
        level:           90%
      - skill:           RKE / Rancher Kubernetes Engine
        level:           90%
      - skill:           CoreOS / Container Linux
        level:           65%
      - skill:           Cloud Foundry
        level:           50%
      - skill:           Helm / Helmfile
        level:           90%
      - skill:           MinIO
        level:           80%
      - skill:           cert-manager
        level:           75%
      - skill:           Rook
        level:           70%
      - skill:           KubeDB
        level:           70%
      - skill:           Istio
        level:           50%
      - skill:           Azure
        level:           50%
      - skill:           OVH Cloud
        level:           40%
      - skill:           AWS
        level:           30%

      - section:         Supervision
      - skill:           Prometheus
        level:           75%
      - skill:           Loki
        level:           75%
      - skill:           Grafana
        level:           75%
      - skill:           Sentry
        level:           60%
      - skill:           Logstash
        level:           60%
      - skill:           Kibana
        level:           50%

      - section:         Provisioning
      - skill:           Ansible
        level:           85%
      - skill:           Vagrant / VirtualBox
        level:           85%
      - skill:           Terraform
        level:           75%
      - skill:           MAAS
        level:           66%

      - section:         Cloud Computing
      - skill:           Hadoop/MapReduce
        level:           90%
      - skill:           HBase
        level:           90%
      - skill:           Oozie
        level:           60%
      - skill:           Cassandra
        level:           40%

      - section:         Middleware
      - skill:           MQTT
        level:           80%
      - skill:           ActiveMQ
        level:           65%
      - skill:           RabbitMQ
        level:           65%
      - skill:           Kafka
        level:           60%

      - section:         Authentification / Autorisations
      - skill:           Keycloak
        level:           75%
      - skill:           HashiCorp Vault
        level:           70%
      - skill:           LDAP
        level:           70%
      - skill:           OpenLDAP
        level:           65%
      - skill:           Active Directory
        level:           40%

      - section:         Java
      - skill:           Java 21+
        level:           100%
      - skill:           Maven
        level:           90%
      - skill:           Gradle
        level:           70%
      - skill:           Spring / Spring Boot
        level:           90%
      # - skill:           Hibernate / JPA
      #   level:           95%
      # - skill:           Jersey / JAX-RS
      #   level:           95%
      # - skill:           JAXB
      #   level:           95%
      - skill:           Gatling
        level:           85%
      - skill:           ProGuard
        level:           80%
      - skill:           javacc
        level:           80%

      - section:         Langages et frameworks Web
      - skill:           Javascript ES2023+
        level:           90%
      - skill:           TypeScript
        level:           70%
      - skill:           Angular / RxJs / NgRx
        level:           85%
      - skill:           Vue.js / Vuex / Vuetify
        level:           85%
      - skill:           NodeJS / Express
        level:           75%
      - skill:           HTML 5
        level:           80%
      - skill:           CSS 3
        level:           70%
      - skill:           jQuery / jQuery UI
        level:           90%
      - skill:           Bootstrap
        level:           60%
      - skill:           Tailwind CSS
        level:           50%
      - skill:           Less CSS
        level:           50%
      - skill:           SAAS
        level:           50%
      - skill:           Ionic Angular
        level:           50%
      - skill:           Grails
        level:           50%

      - section:         Développement
      - skill:           IntelliJ
        level:           95%
      - skill:           VS Code
        level:           90%
      - skill:           Suite Atlassian (Jira, Confluence, Bitbucket et Bamboo)
        level:           60%
      - skill:           Gitlab CI/CD
        level:           90%
      - skill:           GitHub Actions
        level:           65%
      - skill:           Git
        level:           95%
      - skill:           Subversion
        level:           95%

      - section:         Bases de données
      - skill:           PostgreSQL
        level:           95%
      - skill:           MySQL
        level:           85%
      - skill:           H2
        level:           84%
      - skill:           SQLite
        level:           70%
      - skill:           Elasticsearch
        level:           50%
      - skill:           MongoDB
        level:           50%

      - section:         Sysadmin
      - skill:           Ubuntu / Debian
        level:           95%
      - skill:           Open/LibreSSL
        level:           90%
      - skill:           Apache HTTPD
        level:           90%
      - skill:           Nginx
        level:           80%
      - skill:           Træfik
        level:           70%
      - skill:           HAproxy
        level:           60%
      - skill:           GitLab / GitLab CI/CD
        level:           95%
      - skill:           SonarQube
        level:           95%
      - skill:           Nexus Repository
        level:           95%
      - skill:           Docker registry
        level:           95%
      - skill:           Mattermost
        level:           70%
      - skill:           Mediawiki
        level:           80%
      - skill:           Apache Archiva
        level:           85%

      # - section:         Dans les limbes (oubliettes)
      # - skill:           PHP
      #   level:           80%
      # - skill:           TCL/Tk
      #   level:           80%
      # - skill:           Python 3
      #   level:           40%

  footer:
    copyright:           "Oui au numérique, non au digital (sauf cadre intime)"
